### ISSUE TITLE
Mod compatibilty Vampirism - Flying

### ISSUE THREAD

**Issue by maxanier** [IceMetalPunk/TotemEssentials#3]
My mod Vampirism adds the ability to transform into a bat and fly similar to creative mode.
Unfortunately  there seems to be a compatibilty issue with this mod https://github.com/TeamLapen/Vampirism/issues/230

Both TotemEssentials and Vampirism use the player.capabilities.allowFlying for this as far as I can tell.
However, TotemEssentials seems to check/set the flying abilities each living update tick 
https://github.com/IceMetalPunk/TotemEssentials/blob/d9d580c76c89e3c07fa715e9d882ed64fd8bbc49/src/main/java/com/icemetalpunk/totemessentials/events/TEEnsouledEvents.java#L103-L130
and thereby resets Vampirism flight abilities (as it is only set on (de)activating the bat mode).

I'm not sure what the best solution for this issue is, but maybe it is possible to only set the flying abilities on (de)equipping the item in TotemEssentials

**Comment by IceMetalPunk** [comment]
Even if I set the flying state on equip/unequip, then unequipping the totem would still interfere with Vampirism bat flight. I think the best solution (though not perfect) is to, rather than turning off creative flight when you unequip the totem, reset your flight status to whatever it was before you equipped the totem. I'll see if I can make that happen. Thanks for the report.

**Comment by IceMetalPunk** [comment]
Okay, this should now be fixed in release v1.0.2; I tested with the latest Vampirism mod release, and everything seems to work now :) Closing this issue; please re-submit if you notice anything that's still bugged that I've missed.

**Comment by maxanier** [comment]
That was quick, sounds like a good solution 👍
